DROP TABLE att_base_info;
CREATE TABLE att_base_info ( uuid varchar(36) NOT NULL COMMENT '逻辑主键', att_address varchar(200) COMMENT '附件地址', att_name varchar(300) COMMENT '附件名称', att_type varchar(2) COMMENT '附件类型', att_size varchar(20) COMMENT '附件大小', att_classification varchar(1) COMMENT '附件类别', PRIMARY KEY (uuid) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE bus_att_info;
CREATE TABLE bus_att_info ( uuid varchar(36) NOT NULL COMMENT '逻辑主键', att_id varchar(36) COMMENT '附件ID', relation_id varchar(36) COMMENT '关系ID', type varchar(1) COMMENT '类型', att_seq int COMMENT '附件序号', PRIMARY KEY (uuid) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE dictionary_base_info;
CREATE TABLE dictionary_base_info ( uuid varchar(36) NOT NULL COMMENT '逻辑主键', dict_type_code varchar(36) COMMENT '字典类型代码', dict_type_name varchar(300) COMMENT '字典类型名称', dict_code varchar(36) COMMENT '字典编码', dict_value varchar(300) COMMENT '字典值', dict_parent_uuid varchar(36) COMMENT '字典上级主键', PRIMARY KEY (uuid) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE dynamic_base_info;
CREATE TABLE dynamic_base_info ( uuid varchar(36) NOT NULL COMMENT '逻辑主键', title varchar(90) COMMENT '标题', comment varchar(6000) COMMENT '内容', commended_num int COMMENT '点赞数', collection_num int COMMENT '收藏数', publisher_no varchar(36) COMMENT '发布人ID', publisher_time datetime COMMENT '发布时间', dynamic_status varchar(1) COMMENT '动态状态', shared_num int COMMENT '被分享数', commented_num int, img_url varchar(1024), commented_last_time datetime, PRIMARY KEY (uuid) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE dynamic_ext_info;
CREATE TABLE dynamic_ext_info ( uuid varchar(36) NOT NULL COMMENT '逻辑主键', dynamic_no varchar(36) COMMENT '动态ID', type varchar(1) COMMENT '类型', related_user_id varchar(36) COMMENT '关联用户ID', PRIMARY KEY (uuid) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE find_base_ext;
CREATE TABLE find_base_ext ( uuid varchar(36) NOT NULL COMMENT '逻辑主键', activity_no varchar(36) COMMENT '动态ID', type varchar(1) COMMENT '类型', relation_user_id varchar(36) COMMENT '关联用户ID', PRIMARY KEY (uuid) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE find_base_info;
CREATE TABLE find_base_info ( uuid varchar(36) NOT NULL COMMENT '逻辑主键', publisher_no varchar(36) COMMENT '发布人编号', publisher_time datetime COMMENT '发布时间', activity_title varchar(300) COMMENT '活动标题', activity_content blob COMMENT '活动内容', commended_num int COMMENT '被赞数', collection_num int COMMENT '收藏数', follow_num int COMMENT '评论数', share_num int COMMENT '分享数', province varchar(30) COMMENT '省份/直辖市', city varchar(30) COMMENT '地级市', area varchar(30) COMMENT '县/区', village varchar(30) COMMENT '街道/村', publish_address varchar(300) COMMENT '发布详细地址', PRIMARY KEY (uuid) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE find_publisher_base;
CREATE TABLE find_publisher_base ( uuid varchar(36) NOT NULL COMMENT '逻辑主键', subject_photo_no varchar(36) COMMENT '主题背景图片ID', logo_photo_no varchar(36) COMMENT 'logo图片ID', publishing_enterprise_name varchar(300) COMMENT '发布企业名称', publishing_enterprise_sumary varchar(3000) COMMENT '发布企业简介', maintenance_time datetime COMMENT '维护时间', PRIMARY KEY (uuid) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE mes_com_ext;
CREATE TABLE mes_com_ext ( uuid varchar(36) NOT NULL COMMENT '逻辑主键', message_uuid varchar(36) COMMENT '消息主键', related_uuid varchar(36) COMMENT '关联主键', related_type varchar(1) COMMENT '关联类型', PRIMARY KEY (uuid) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE mes_com_info;
CREATE TABLE mes_com_info ( uuid varchar(36) NOT NULL COMMENT '逻辑主键', message_parent_no varchar(36) COMMENT '消息父ID', message_comment varchar(3000) COMMENT '消息内容', message_publisher_no varchar(36) COMMENT '消息发布人ID', message_publisher_time datetime COMMENT '消息发布时间', message_way varchar(1) COMMENT '消息方式', PRIMARY KEY (uuid) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE opinion_feedback;
CREATE TABLE opinion_feedback ( uuid varchar(36) NOT NULL COMMENT '逻辑主键', opinion_type varchar(1) COMMENT '意见类型', opinion_code varchar(3) COMMENT '意见代码', opinion_code_comment varchar(300) COMMENT '意见代码内容', opinion_comment varchar(3000) COMMENT '意见内容', att_uuid varchar(36) COMMENT '附件主键', feedback_no varchar(36) COMMENT '反馈人编号', feedback_time datetime COMMENT '反馈时间', PRIMARY KEY (uuid) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE tag_base_info;
CREATE TABLE tag_base_info ( tag_no varchar(36) NOT NULL COMMENT '标签编号', tag_name varchar(300) COMMENT '标签名称', tag_type_no varchar(36) COMMENT '标签类别编号', tag_type_name varchar(300) COMMENT '标签类别名称', PRIMARY KEY (tag_no) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE tag_dynamic_relation;
CREATE TABLE tag_dynamic_relation ( uuid varchar(36) NOT NULL COMMENT '逻辑主键', activity_no varchar(36) COMMENT '动态编号', tag_no varchar(36) COMMENT '标签编号', PRIMARY KEY (uuid) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE user_base_info;
CREATE TABLE user_base_info ( user_no varchar(36) NOT NULL COMMENT '用户编号', head_sculpture varchar(36) COMMENT '头像（附件ID）', my_nickname varchar(100) COMMENT '我的昵称', my_phone varchar(11) COMMENT '我的手机号', commended_num int COMMENT '被赞数', fans_num int COMMENT '粉丝数', follow_num int COMMENT '关注数', my_tag varchar(500) COMMENT '自评标签', my_position varchar(500) COMMENT '地理位置', sex varchar(1) COMMENT '性别', birthday varchar(8) COMMENT '生日', my_address varchar(300) COMMENT '常住地址', signature varchar(300) COMMENT '签名', shared_num int COMMENT '被分享数', share_num int COMMENT '分享数', wechat_num varchar(20) COMMENT '微信号', qq_num varchar(20) COMMENT 'QQ号', blog_num varchar(20) COMMENT '微博号', register_time datetime COMMENT '注册时间', PRIMARY KEY (user_no) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE user_ext_info;
CREATE TABLE user_ext_info ( uuid varchar(36) NOT NULL COMMENT '逻辑主键', user_no varchar(36) COMMENT '用户编号', type varchar(1) COMMENT '类型', related_user_no varchar(36) COMMENT '关联用户编号', PRIMARY KEY (uuid) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
DROP TABLE user_t;
CREATE TABLE user_t ( id int NOT NULL AUTO_INCREMENT, user_name varchar(40) NOT NULL, password varchar(255) NOT NULL, age int(4) NOT NULL, PRIMARY KEY (id) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
